# Generated by Django 4.1.7 on 2023-02-28 16:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.CharField(max_length=100)),
                ('CANTIDAD', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('PRECIO', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.CharField(max_length=100)),
                ('DIA', models.CharField(choices=[('LUNES', 'LUNES'), ('MARTES', 'MARTES'), ('MIERCOLES', 'MIERCOLES'), ('JUEVES', 'JUEVES'), ('VIERNES', 'VIERNES'), ('SABADO', 'SABADO'), ('DOMINGO', 'DOMINGO')], max_length=100)),
                ('REPARTIDOR', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalidaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FECHA', models.DateTimeField(auto_now=True)),
                ('ATIENDE', models.CharField(max_length=100)),
                ('REPARTIDOR', models.CharField(max_length=100)),
                ('OBSERVACIONES', models.CharField(max_length=200)),
                ('STATUS', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('REALIZADO', 'REALIZADO'), ('CANCELADO', 'CANCELADO')], max_length=100)),
                ('RUTA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoSalidaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CANTIDAD_RUTA', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('STATUS', models.CharField(choices=[('CARGADO', 'CARGADO'), ('VENDIDO', 'VENDIDO'), ('CANCELADO', 'CANCELADO')], max_length=100)),
                ('PRODUCTO_RUTA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
                ('SALIDA_RUTA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salida_ruta_productos', to='api.salidaruta')),
            ],
        ),
        migrations.CreateModel(
            name='DevolucionSalidaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATIDAD_DEVOLUCION', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('STATUS', models.CharField(choices=[('REALIZADO', 'REALIZADO'), ('PENDIENTE', 'PENDIENTE')], max_length=100)),
                ('PRODUCTO_DEVOLUCION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
                ('SALIDA_RUTA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salida_ruta_devoluciones', to='api.salidaruta')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.CharField(max_length=100)),
                ('RUTA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruta_clientes', to='api.ruta')),
            ],
        ),
    ]
