# Generated by Django 4.1.7 on 2023-02-28 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_preciocliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosalidaruta',
            name='CANTIDAD_DISPONIBLE',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
