# Generated by Django 4.1.7 on 2023-03-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_productosalidaruta_cantidad_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaruta',
            name='STATUS',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PROGRESO', 'PROGRESO'), ('REALIZADO', 'REALIZADO'), ('CANCELADO', 'CANCELADO')], max_length=100),
        ),
    ]
